# Generated by Django 5.2.6 on 2025-12-22 15:53

import crmspagi.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Logo Principal', max_length=100)),
                ('imagem', models.ImageField(storage=crmspagi.storage_backends.PublicMediaStorage(), upload_to='sistema/banners/', verbose_name='Imagem do Banner/Logo')),
                ('ativo', models.BooleanField(default=True)),
                ('usar_imagem', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração de Banner',
                'verbose_name_plural': 'Banners do Sistema',
            },
        ),
    ]
