# Generated by Django 5.2.6 on 2026-07-09 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Módulo do Sistema',
                'verbose_name_plural': 'Módulos do Sistema',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoIntegracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolution_api_url', models.CharField(blank=True, max_length=255, verbose_name='Evolution API - URL')),
                ('evolution_api_key', models.CharField(blank=True, max_length=255, verbose_name='Evolution API - Chave')),
                ('evolution_instance', models.CharField(blank=True, max_length=100, verbose_name='Evolution API - Instância')),
                ('evo_crm_api_url', models.CharField(blank=True, max_length=255, verbose_name='EVO CRM - URL da API')),
                ('evo_crm_api_token', models.CharField(blank=True, max_length=255, verbose_name='EVO CRM - Token')),
                ('evo_crm_pipeline_id', models.CharField(blank=True, max_length=100, verbose_name='EVO CRM - Pipeline ID')),
                ('evo_crm_pipeline_stage_id', models.CharField(blank=True, max_length=100, verbose_name='EVO CRM - Stage ID')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Integrações Externas',
                'verbose_name_plural': 'Configurações de Integrações Externas',
            },
        ),
        migrations.CreateModel(
            name='WebhookIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome / Função')),
                ('slug', models.SlugField(help_text='Ex: WHATSAPP_VENDA_REJEITADA. Não altere depois que o evento já estiver integrado.', unique=True, verbose_name='Identificador (usado no código)')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='Quando dispara?')),
                ('url', models.URLField(blank=True, help_text='Em branco usa a variável de ambiente padrão (se houver).', max_length=500)),
                ('ativo', models.BooleanField(default=True, verbose_name='Envio ativo?')),
                ('sistema', models.BooleanField(default=False, editable=False, verbose_name='Evento nativo do sistema')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook de Integração',
                'verbose_name_plural': 'Webhooks de Integração',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PermissaoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pode_visualizar', models.BooleanField(default=False, verbose_name='Visualizar')),
                ('pode_criar', models.BooleanField(default=False, verbose_name='Criar')),
                ('pode_editar', models.BooleanField(default=False, verbose_name='Editar')),
                ('pode_excluir', models.BooleanField(default=False, verbose_name='Excluir')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes', to='configuracoes.modulosistema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissoes_modulo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão de Módulo',
                'verbose_name_plural': 'Permissões de Módulo',
                'unique_together': {('user', 'modulo')},
            },
        ),
    ]
