# Generated by Django 5.2.6 on 2026-07-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_configuracaointegracoes_provedor_imagem_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaointegracoes',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, verbose_name='OpenAI - Chave da API'),
        ),
        migrations.AlterField(
            model_name='configuracaointegracoes',
            name='provedor_imagem_ia',
            field=models.CharField(choices=[('GEMINI', 'Gemini (Google)'), ('LEONARDO', 'Leonardo.Ai'), ('OPENAI', 'OpenAI (GPT Image)')], default='GEMINI', max_length=20, verbose_name='Provedor de geração de imagem (Marketing IA)'),
        ),
    ]
