# Generated by Django 5.2.6 on 2026-07-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_configuracaointegracoes_openai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaointegracoes',
            name='gemini_image_model',
            field=models.CharField(choices=[('gemini-2.5-flash-image', 'Gemini 2.5 Flash Image (atual — será descontinuado em out/2026)'), ('gemini-3.1-flash-image-preview', 'Gemini 3.1 Flash Image — "Nano Banana 2" (rápido e barato)'), ('gemini-3-pro-image-preview', 'Gemini 3 Pro Image — "Nano Banana Pro" (melhor qualidade)')], default='gemini-2.5-flash-image', max_length=60, verbose_name='Gemini - Modelo de imagem'),
        ),
        migrations.AddField(
            model_name='configuracaointegracoes',
            name='leonardo_model_id',
            field=models.CharField(choices=[('05ce0082-2d80-4a2d-8653-4d1c85e2418e', 'Lucid Realism (fotorrealista — recomendado)'), ('7b592283-e8a7-4c5a-9ba6-d18c31f258b9', 'Lucid Origin'), ('de7d3faf-762f-48e0-b3b7-9d0ac3a3fcf3', 'Leonardo Phoenix 1.0'), ('1e60896f-3c26-4296-8ecc-53e2afecc132', 'Leonardo Diffusion XL (antigo, não recomendado)')], default='05ce0082-2d80-4a2d-8653-4d1c85e2418e', max_length=60, verbose_name='Leonardo.Ai - Modelo'),
        ),
        migrations.AddField(
            model_name='configuracaointegracoes',
            name='openai_image_model',
            field=models.CharField(choices=[('gpt-image-1-mini', 'GPT Image 1 Mini (mais barato)'), ('gpt-image-1', 'GPT Image 1'), ('gpt-image-1.5', 'GPT Image 1.5'), ('gpt-image-2', 'GPT Image 2 (melhor qualidade)')], default='gpt-image-1-mini', max_length=30, verbose_name='OpenAI - Modelo'),
        ),
        migrations.AddField(
            model_name='configuracaointegracoes',
            name='openai_image_quality',
            field=models.CharField(choices=[('low', 'Baixa (mais barata)'), ('medium', 'Média'), ('high', 'Alta (melhor qualidade, mais cara)')], default='medium', max_length=10, verbose_name='OpenAI - Qualidade'),
        ),
    ]
