# Generated by Django 5.2.6 on 2026-07-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0005_configuracaointegracoes_gemini_image_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaointegracoes',
            name='prompt_imagem',
            field=models.TextField(blank=True, default="Use a foto enviada como referência do veículo real (mantenha a carroceria, cor e detalhes fiéis ao original, sem alterar o veículo). Recrie a cena colocando o veículo em um showroom moderno e bem iluminado (ou pátio externo elegante ao entardecer), com reflexo sutil no chão, aparência profissional de anúncio publicitário para redes sociais, formato quadrado (1:1), alta qualidade fotorrealista. Não inclua nenhum texto, logotipo ou marca d'água na imagem.", help_text='Usado por Gemini e OpenAI, que recebem a foto do veículo junto com o prompt.', verbose_name='Prompt da cena (Gemini / OpenAI)'),
        ),
        migrations.AddField(
            model_name='configuracaointegracoes',
            name='prompt_imagem_leonardo',
            field=models.TextField(blank=True, default='Professional automotive advertisement photo, the vehicle placed in a modern, well-lit showroom (or an elegant outdoor lot at dusk), subtle floor reflection, photorealistic, high quality, social media ad style, square composition. No text, no logo, no watermark.', help_text="Só a descrição da cena (em inglês, se possível) — a foto do veículo vai separada, não mencione 'a foto enviada'.", verbose_name='Prompt da cena (Leonardo.Ai)'),
        ),
    ]
