# Generated by Django 5.2.6 on 2026-07-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0006_configuracaointegracoes_prompt_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaointegracoes',
            name='provedor_imagem_ia',
            field=models.CharField(choices=[('GEMINI', 'Gemini (Google)'), ('LEONARDO', 'Leonardo.Ai'), ('OPENAI', 'OpenAI (GPT Image)'), ('OVERLAY', 'Sem IA de imagem (texto sobre a foto real)')], default='GEMINI', max_length=20, verbose_name='Provedor de geração de imagem (Marketing IA)'),
        ),
    ]
