# Generated by Django 5.2.6 on 2026-07-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0007_alter_configuracaointegracoes_provedor_imagem_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaointegracoes',
            name='resolucao_imagem_overlay',
            field=models.CharField(choices=[('1080x1080', 'Quadrado 1080x1080 (Feed)'), ('1080x1350', 'Retrato 1080x1350 (Feed 4:5)'), ('1080x1920', 'Vertical 1080x1920 (Stories/Reels)')], default='1080x1080', max_length=12, verbose_name='Resolução do overlay'),
        ),
        migrations.AddField(
            model_name='configuracaointegracoes',
            name='template_imagem_overlay',
            field=models.CharField(choices=[('FAIXA_INFERIOR', 'Faixa inferior (chamada + título + preço empilhados)'), ('SELO_DIAGONAL', 'Selo diagonal de oferta + faixa inferior compacta'), ('CARTAO_CENTRAL', 'Cartão arredondado flutuante')], default='FAIXA_INFERIOR', max_length=20, verbose_name='Template do overlay'),
        ),
    ]
