# Generated by Django 5.2.6 on 2026-07-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0008_configuracaointegracoes_resolucao_imagem_overlay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaointegracoes',
            name='notificar_leads_atrasados',
            field=models.BooleanField(default=True, help_text='Desliga o alerta diário (job check_overdue_clients) pro vendedor e admins quando o próximo contato de um lead já passou.', verbose_name='Notificar leads com contato atrasado'),
        ),
    ]
