# Generated by Django 5.2.6 on 2026-02-27 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0002_funcionario_opta_vt_funcionario_valor_diario_vt'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data do Ponto')),
                ('entrada', models.TimeField(blank=True, null=True, verbose_name='Entrada')),
                ('foto_entrada', models.TextField(blank=True, null=True, verbose_name='Foto Entrada (Base64)')),
                ('saida_almoco', models.TimeField(blank=True, null=True, verbose_name='Saída Almoço')),
                ('foto_saida_almoco', models.TextField(blank=True, null=True, verbose_name='Foto Saída Almoço')),
                ('retorno_almoco', models.TimeField(blank=True, null=True, verbose_name='Retorno Almoço')),
                ('foto_retorno_almoco', models.TextField(blank=True, null=True, verbose_name='Foto Retorno Almoço')),
                ('saida', models.TimeField(blank=True, null=True, verbose_name='Saída')),
                ('foto_saida', models.TextField(blank=True, null=True, verbose_name='Foto Saída')),
                ('ip_registrado', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP da Máquina')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos', to='funcionarios.funcionario')),
            ],
            options={
                'verbose_name': 'Registro de Ponto',
                'verbose_name_plural': 'Registros de Ponto',
                'unique_together': {('funcionario', 'data')},
            },
        ),
    ]
