# Generated by Django 5.2.6 on 2026-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_ponto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroponto',
            options={'verbose_name': 'Registo de Ponto', 'verbose_name_plural': 'Registos de Ponto'},
        ),
        migrations.AddField(
            model_name='registroponto',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
    ]
