# Generated by Django 5.2.6 on 2026-02-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_ponto', '0002_alter_registroponto_options_registroponto_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_permitido', models.CharField(default='*', help_text="Coloque o IP Fixo da loja ou deixe '*' para aceitar qualquer IP.", max_length=50, verbose_name='IP Permitido da Loja')),
                ('latitude_loja', models.CharField(default='-25.4284', max_length=50, verbose_name='Latitude da Loja (Central)')),
                ('longitude_loja', models.CharField(default='-49.2733', max_length=50, verbose_name='Longitude da Loja (Central)')),
                ('raio_permitido', models.IntegerField(default=100, help_text='Distância máxima que o funcionário pode estar da loja para bater o ponto.', verbose_name='Raio Permitido (em metros)')),
            ],
            options={
                'verbose_name': 'Configuração do Ponto',
                'verbose_name_plural': 'Configurações do Ponto',
            },
        ),
        migrations.AlterModelOptions(
            name='registroponto',
            options={'verbose_name': 'Registro de Ponto', 'verbose_name_plural': 'Registros de Ponto'},
        ),
    ]
