# Generated by Django 5.2.6 on 2026-07-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_ponto', '0007_fechamentofolhaponto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoponto',
            name='ip_permitido',
            field=models.CharField(default='*', help_text="Coloque o IP fixo da loja ou deixe '*' para aceitar qualquer IP.", max_length=50, verbose_name='IP Permitido da Loja'),
        ),
    ]
