# Generated by Django 5.2.6 on 2026-02-07 15:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone/WhatsApp')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço Completo')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Salário Base (R$)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Colaborador Ativo?')),
                ('banco', models.CharField(max_length=100, verbose_name='Nome do Banco')),
                ('agencia', models.CharField(max_length=20, verbose_name='Agência')),
                ('conta', models.CharField(max_length=30, verbose_name='Nº da Conta')),
                ('tipo_conta', models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Poupança'), ('SALARIO', 'Conta Salário')], default='CORRENTE', max_length=20, verbose_name='Tipo de Conta')),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave Pix')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_funcionais', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema')),
            ],
            options={
                'verbose_name': 'Cadastro Funcional',
                'verbose_name_plural': 'Cadastros Funcionais',
            },
        ),
    ]
