# Generated by Django 5.2.6 on 2026-02-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='opta_vt',
            field=models.BooleanField(default=False, verbose_name='Opta por Vale Transporte?'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='valor_diario_vt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Valor Diário VT (Ida+Volta)'),
        ),
    ]
