# Generated by Django 5.2.6 on 2026-02-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_opta_vt_funcionario_valor_diario_vt'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='foto_biometria',
            field=models.ImageField(blank=True, null=True, upload_to='biometria/', verbose_name='Foto Base para Biometria Facial'),
        ),
    ]
