# Generated by Django 5.2.6 on 2026-02-27 17:24

import crmspagi.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_funcionario_foto_biometria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto_biometria',
            field=models.ImageField(blank=True, null=True, storage=crmspagi.storage_backends.PublicMediaStorage(), upload_to='biometria/', verbose_name='Foto Base para Biometria Facial'),
        ),
    ]
