# Generated by Django 5.2.6 on 2026-07-03 20:18

import crmspagi.storage_backends
import django.core.validators
import funcionarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_funcionario_data_ultimo_dia_trabalhado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='foto_biometria',
            field=models.ImageField(blank=True, null=True, storage=crmspagi.storage_backends.PublicMediaStorage(), upload_to='biometria/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png']), funcionarios.models.validar_tamanho_foto_biometria], verbose_name='Foto Base para Biometria Facial'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo_conta',
            field=models.CharField(choices=[('CORRENTE', 'Conta Corrente'), ('POUPANCA', 'Conta Poupança'), ('SALARIO', 'Conta Salário')], default='CORRENTE', max_length=20, verbose_name='Tipo de Conta'),
        ),
    ]
