# Generated by Django 5.2.6 on 2025-11-01 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('outorgante_nome', models.CharField(max_length=255, verbose_name='Nome do Outorgante (Vendedor do Veículo)')),
                ('tipo_documento', models.CharField(choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ')], default='CPF', max_length=4, verbose_name='Tipo de Documento')),
                ('outorgante_documento', models.CharField(max_length=20, verbose_name='CPF/CNPJ do Outorgante')),
                ('veiculo_marca_modelo', models.CharField(max_length=100, verbose_name='Marca/Modelo')),
                ('veiculo_ano_fab', models.CharField(max_length=4, verbose_name='Ano Fabricação')),
                ('veiculo_ano_mod', models.CharField(max_length=4, verbose_name='Ano Modelo')),
                ('veiculo_placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('veiculo_cor', models.CharField(max_length=50, verbose_name='Cor Predominante')),
                ('veiculo_renavam', models.CharField(max_length=20, verbose_name='RENAVAM')),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procuracoes_geradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Procuração',
                'verbose_name_plural': 'Procurações',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
