# Generated by Django 5.2.6 on 2025-11-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outorgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=20, unique=True, verbose_name='CPF')),
            ],
            options={
                'verbose_name': 'Outorgado',
                'verbose_name_plural': 'Outorgados',
                'ordering': ['nome'],
            },
        ),
    ]
