# Generated by Django 5.2.6 on 2026-01-17 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendedorRodizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True, verbose_name='Participa do Rodízio?')),
                ('ultima_atribuicao', models.DateTimeField(blank=True, null=True, verbose_name='Última Atribuição')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor número recebe primeiro')),
                ('vendedor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_rodizio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Rodízio',
                'verbose_name_plural': 'Configurações de Rodízio',
                'ordering': ['ultima_atribuicao', 'ordem'],
            },
        ),
    ]
