# Generated by Django 5.2.6 on 2026-01-17 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribuicao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedorrodizio',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Menor número recebe primeiro em caso de empate'),
        ),
    ]
