# Generated by Django 5.2.6 on 2025-10-12 15:29

import avaliacoes.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('valor_pretendido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('valor_avaliado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('finalizado', 'Finalizado')], default='disponivel', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to=avaliacoes.models.get_upload_path)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='avaliacoes.avaliacao')),
            ],
        ),
    ]
