# Generated by Django 5.2.6 on 2025-10-13 21:10

import avaliacoes.models
import crmspagi.storage_backends
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='ano',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='cadastrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_cadastradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='marca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='avaliacaofoto',
            name='foto',
            field=models.ImageField(storage=crmspagi.storage_backends.PublicMediaStorage(), upload_to=avaliacoes.models.get_upload_path),
        ),
    ]
