# Generated by Django 5.2.6 on 2025-10-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_avaliacao_ano_avaliacao_cadastrado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='tipo_veiculo',
            field=models.CharField(choices=[('carros', 'Carro'), ('motos', 'Moto'), ('caminhoes', 'Caminhão')], default='carros', max_length=10, verbose_name='Tipo de Veículo'),
        ),
    ]
