# Generated by Django 5.2.6 on 2025-12-22 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=150, verbose_name='Cliente')),
                ('veiculo', models.CharField(max_length=100, verbose_name='Veículo')),
                ('ano', models.CharField(max_length=20, verbose_name='Ano')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('valor_veiculo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Veículo')),
                ('banco', models.CharField(max_length=50, verbose_name='Banco')),
                ('qtd_parcelas', models.IntegerField(verbose_name='Qtd Parcelas')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Parcela')),
                ('valor_financiado', models.DecimalField(decimal_places=2, help_text='Valor líquido financiado', max_digits=12, verbose_name='Valor Financiado')),
                ('porcentagem_retorno', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Retorno')),
                ('valor_retorno', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Valor Retorno (R$)')),
                ('status', models.CharField(choices=[('NOVA', 'Nova'), ('EM_ANALISE', 'Em Análise'), ('APROVADA', 'Aprovada'), ('EM_ASSINATURA', 'Em Assinatura'), ('RECUSADA', 'Recusada'), ('CANCELADA', 'Cancelada'), ('EM_PAGAMENTO', 'Em Pagamento'), ('PAGO', 'Pago'), ('FINALIZADO', 'Finalizado')], default='NOVA', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha de Financiamento',
                'verbose_name_plural': 'Fichas de Financiamento',
                'ordering': ['-data_atualizacao'],
            },
        ),
    ]
