# Generated by Django 5.2.6 on 2025-12-21 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=20)),
                ('cor', models.CharField(max_length=30)),
                ('tipo', models.CharField(choices=[('TANQUE', 'Tanque Cheio'), ('TRANSFERENCIA', 'Transferência Grátis'), ('REPARO', 'Reparo / Manutenção'), ('ACESSORIO', 'Acessório (Insulfilm, Som, etc)'), ('DOCUMENTACAO', 'Documentação / IPVA'), ('OUTRO', 'Outros')], max_length=20)),
                ('descricao', models.TextField(help_text='Ex: Troca de pastilhas de freio ou Tanque cheio na entrega.', verbose_name='Descrição Detalhada')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Aprovação'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizacoes_gerenciadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Autorização',
                'verbose_name_plural': 'Autorizações',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
