# Generated by Django 5.2.6 on 2025-11-06 16:28

import crmspagi.storage_backends
import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_userloginactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=crmspagi.storage_backends.PublicMediaStorage(), upload_to=usuarios.models.get_avatar_upload_path, verbose_name='Foto de Perfil'),
        ),
    ]
