# Generated by Django 5.2.6 on 2026-01-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pode_distribuir_leads',
            field=models.BooleanField(default=False, verbose_name='Permissão Extra: Pode Distribuir Leads?'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nivel_acesso',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente'), ('ADMIN', 'Administrador'), ('DISTRIBUIDOR', 'Distribuidor (Apenas)')], default='VENDEDOR', max_length=20),
        ),
    ]
