# Generated by Django 5.2.6 on 2026-02-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_profile_pode_distribuir_leads_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nivel_acesso',
            field=models.CharField(choices=[('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente'), ('ADMIN', 'Administrador'), ('DISTRIBUIDOR', 'Distribuidor (Apenas)'), ('CONSIGNADOR', 'Consignador')], default='VENDEDOR', max_length=20),
        ),
    ]
