# Generated by Django 5.2.6 on 2026-02-27 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_profile_nivel_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pode_acessar_financeiro',
            field=models.BooleanField(default=False, verbose_name='Pode acessar o Financeiro? (Ver e Lançar)'),
        ),
    ]
