# Generated by Django 5.2.6 on 2026-07-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_remove_modulepermission_modulo_whatsapp'),
        ('configuracoes', '0002_seed_e_migra_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notificacao_whatsapp',
            field=models.BooleanField(default=True, verbose_name='Notificações via WhatsApp habilitadas?'),
        ),
        migrations.DeleteModel(
            name='ModulePermission',
        ),
    ]
