# Generated by Django 5.2.6 on 2025-10-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(default='https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1&mute=1&loop=1&playlist=dQw4w9WgXcQ', help_text='O link do vídeo para exibição na TV. Para YouTube, use o link de embed (ex: https://www.youtube.com/embed/SEU_ID?autoplay=1&mute=1&loop=1&playlist=SEU_ID).', verbose_name='URL do Vídeo (Recomendado YouTube Embed ou MP4 direto)')),
                ('titulo', models.CharField(default='Vídeo Promocional', max_length=100, verbose_name='Título do Vídeo')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Configuração de Vídeo da TV',
                'verbose_name_plural': 'Configuração de Vídeo da TV',
            },
        ),
    ]
