# Generated by Django 5.2.6 on 2025-10-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvvideo',
            name='manual_news_ticker',
            field=models.TextField(blank=True, help_text="Texto que será exibido no rodapé da TV, substituindo as notícias da API. Separe as notícias com ' | ' (barra vertical).", null=True, verbose_name='Ticker de Notícias Manual (Opcional)'),
        ),
        migrations.AddField(
            model_name='tvvideo',
            name='newsdata_api_key',
            field=models.CharField(blank=True, default='pub_9a838f4c10ea441382a5a65d67601949', help_text='Chave de acesso para buscar notícias externas (Ex: pub_...)', max_length=50, null=True, verbose_name='Chave API NewsData.io'),
        ),
    ]
