# Generated by Django 5.2.6 on 2025-10-29 23:30

import crmspagi.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadge', '0002_tvvideo_manual_news_ticker_tvvideo_newsdata_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvvideo',
            name='video_mp4',
            field=models.FileField(blank=True, help_text='Use este campo para carregar um arquivo MP4. Se preenchido, terá prioridade sobre a URL do YouTube.', null=True, storage=crmspagi.storage_backends.PublicMediaStorage(), upload_to='tv_videos/', verbose_name='Upload de Vídeo MP4 (Alternativo)'),
        ),
    ]
