# Generated by Django 5.2.6 on 2025-12-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leadge', '0003_tvvideo_video_mp4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título da Novidade')),
                ('imagem', models.ImageField(upload_to='banners/', verbose_name='Imagem do Banner (1200x400 recom.)')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição Curta')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link de Destino (Opcional)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Exibir no Portal?')),
                ('ordem', models.IntegerField(default=0, help_text='Menor número aparece primeiro')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banner de Novidade',
                'verbose_name_plural': 'Banners do Portal',
                'ordering': ['ordem', '-data_criacao'],
            },
        ),
    ]
