# Generated by Django 5.2.6 on 2026-02-27 13:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECEITA', 'Receita / Crédito'), ('DESPESA', 'Despesa / Conta')], max_length=10, verbose_name='Tipo de Transação')),
                ('categoria', models.CharField(choices=[('FIXA', 'Conta Fixa (Água, Luz, Aluguel)'), ('VARIAVEL', 'Despesa Variável (Limpeza, Material)'), ('VEICULO', 'Despesa com Veículo (Oficina, Peças)'), ('RETORNO_FIN', 'Retorno de Financiamento'), ('BONUS', 'Bônus / Premiação'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Categoria')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('data_vencimento', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Vencimento/Recebimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data Efetiva (Pago/Recebido)')),
                ('efetivado', models.BooleanField(default=False, verbose_name='Efetivado?')),
                ('recorrente', models.BooleanField(default=False, verbose_name='Conta Fixa Mensal? (Repetir mês seguinte)')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, verbose_name='Placa do Veículo')),
                ('modelo_veiculo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('ano', models.CharField(blank=True, max_length=9, null=True, verbose_name='Ano')),
            ],
            options={
                'verbose_name': 'Transação Financeira',
                'verbose_name_plural': 'Transações Financeiras',
                'ordering': ['data_vencimento'],
            },
        ),
    ]
