# Generated by Django 5.2.6 on 2026-07-08 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_transacaofinanceira_criado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoMensalFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('ano', models.PositiveIntegerField()),
                ('fechado', models.BooleanField(default=False, verbose_name='Mês fechado?')),
                ('fechado_em', models.DateTimeField(blank=True, null=True)),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_financeiro', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fechamento Mensal Financeiro',
                'verbose_name_plural': 'Fechamentos Mensais Financeiros',
                'unique_together': {('mes', 'ano')},
            },
        ),
    ]
