# Generated by Django 5.2.6 on 2026-01-30 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Credencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Banco/Serviço')),
                ('link', models.URLField(max_length=500, verbose_name='Link de Acesso')),
                ('usuario', models.CharField(max_length=200, verbose_name='Usuário/Login')),
                ('senha', models.CharField(max_length=200, verbose_name='Senha Atual')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações (Token, Passo a passo...)')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credencial de Acesso',
                'verbose_name_plural': 'Credenciais de Acesso',
                'ordering': ['nome'],
            },
        ),
    ]
