# Generated by Django 5.2.6 on 2026-07-12 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_ia', '0005_seed_modulo_sistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_bytes', models.BinaryField()),
                ('imagem_mime_type', models.CharField(default='image/jpeg', max_length=30)),
                ('legenda', models.TextField(blank=True, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=500, null=True)),
                ('prompt_imagem', models.TextField(blank=True, null=True)),
                ('modelo_ia_imagem', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo_ia_texto', models.CharField(blank=True, max_length=100, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previews', to='marketing_ia.veiculoanuncio')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Prévia de Post (IA)',
                'verbose_name_plural': 'Prévias de Post (IA)',
                'ordering': ['-criado_em'],
            },
        ),
    ]
