# Generated by Django 5.2.6 on 2026-07-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_ia', '0006_previewpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculoanuncio',
            name='aceita_troca',
            field=models.BooleanField(default=False, verbose_name='Aceita troca'),
        ),
        migrations.AddField(
            model_name='veiculoanuncio',
            name='ipva_pago',
            field=models.BooleanField(default=False, verbose_name='IPVA pago'),
        ),
        migrations.AddField(
            model_name='veiculoanuncio',
            name='motorizacao',
            field=models.CharField(blank=True, help_text='Ex: 1.0, 1.6 Turbo — raspado do bloco técnico do anúncio, quando disponível.', max_length=30, null=True, verbose_name='Motorização'),
        ),
    ]
