# Generated by Django 5.2.6 on 2026-07-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_ia', '0008_layoutoverlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculoanuncio',
            name='veiculo_completo',
            field=models.BooleanField(default=False, verbose_name='Veículo completo'),
        ),
    ]
