# Generated by Django 5.2.6 on 2026-07-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_ia', '0009_veiculoanuncio_veiculo_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotegeracao',
            name='provedor_imagem_ia',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Provedor de IA de imagem usado'),
        ),
        migrations.AddField(
            model_name='lotegeracao',
            name='resolucao_overlay',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Resolução usada'),
        ),
        migrations.AddField(
            model_name='lotegeracao',
            name='template_overlay',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Template do overlay usado'),
        ),
    ]
