# Generated by Django 5.2.6 on 2026-07-14 22:24

import crmspagi.storage_backends
import django.db.models.deletion
import marketing_ia.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing_ia', '0010_lotegeracao_provedor_imagem_ia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCombinado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveSmallIntegerField(choices=[(2, '2 veículos'), (4, '4 veículos')])),
                ('criterio', models.CharField(choices=[('MESMO_TIPO', 'Mesmo tipo (carro/moto)'), ('MESMA_MARCA', 'Mesma marca')], max_length=20)),
                ('imagem', models.ImageField(storage=crmspagi.storage_backends.PublicMediaStorage(), upload_to=marketing_ia.models.get_post_combinado_upload_path, verbose_name='Imagem combinada gerada')),
                ('legenda', models.TextField(verbose_name='Legenda para redes sociais')),
                ('hashtags', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('APROVADO', 'Aprovado'), ('PUBLICADO', 'Publicado')], default='RASCUNHO', max_length=12)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('veiculos', models.ManyToManyField(related_name='posts_combinados', to='marketing_ia.veiculoanuncio')),
            ],
            options={
                'verbose_name': 'Post Combinado (múltiplos veículos)',
                'verbose_name_plural': 'Posts Combinados (múltiplos veículos)',
                'ordering': ['-gerado_em'],
            },
        ),
    ]
