# Generated by Django 5.2.6 on 2026-02-07 15:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VALE', 'Vale / Adiantamento'), ('ATRASO', 'Faltas / Atrasos'), ('BENEFICIO', 'Convênio / Benefício'), ('OUTROS', 'Outros')], max_length=20)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('data_lancamento', models.DateField(default=django.utils.timezone.now)),
                ('parcelado', models.BooleanField(default=False, verbose_name='Parcelar?')),
                ('qtd_parcelas', models.IntegerField(default=1, verbose_name='Qtd. Parcelas')),
                ('mes_inicio', models.IntegerField(default=2, verbose_name='Mês Início (1-12)')),
                ('ano_inicio', models.IntegerField(default=2026, verbose_name='Ano Início')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descontos', to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_referencia', models.IntegerField()),
                ('ano_referencia', models.IntegerField()),
                ('processada_na_folha', models.BooleanField(default=False)),
                ('desconto_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='folha_pagamento.desconto')),
            ],
            options={
                'ordering': ['ano_referencia', 'mes_referencia'],
            },
        ),
        migrations.CreateModel(
            name='FolhaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_comissoes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salario_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fechada', models.BooleanField(default=False, verbose_name='Folha Fechada?')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago?')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folhas', to='funcionarios.funcionario')),
            ],
            options={
                'ordering': ['-ano', '-mes'],
                'unique_together': {('funcionario', 'mes', 'ano')},
            },
        ),
    ]
