# Generated by Django 5.2.6 on 2026-02-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhapagamento',
            name='desconto_vt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Desc. Vale Transporte'),
        ),
    ]
