# Generated by Django 5.2.6 on 2026-02-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0002_folhapagamento_desconto_vt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição do Feriado')),
                ('data', models.DateField(verbose_name='Data')),
                ('fixo', models.BooleanField(default=False, verbose_name='Feriado Fixo? (Repete todo ano)')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['data'],
            },
        ),
    ]
