# Generated by Django 5.2.6 on 2026-02-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0003_feriado'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhapagamento',
            name='credito_vt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Crédito Vale Transporte'),
        ),
    ]
