# Generated by Django 5.2.6 on 2026-02-10 20:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0004_folhapagamento_credito_vt'),
        ('funcionarios', '0002_funcionario_opta_vt_funcionario_valor_diario_vt'),
    ]

    operations = [
        migrations.AddField(
            model_name='folhapagamento',
            name='total_creditos_manuais',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Outros Créditos'),
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BONUS', 'Bonificação / Prêmio'), ('REEMBOLSO', 'Reembolso de Despesas'), ('HORA_EXTRA', 'Horas Extras'), ('OUTROS', 'Outros Créditos')], max_length=20)),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('data_lancamento', models.DateField(default=django.utils.timezone.now)),
                ('parcelado', models.BooleanField(default=False, verbose_name='Parcelar?')),
                ('qtd_parcelas', models.IntegerField(default=1, verbose_name='Qtd. Parcelas')),
                ('mes_inicio', models.IntegerField(default=2, verbose_name='Mês Início (1-12)')),
                ('ano_inicio', models.IntegerField(default=2026, verbose_name='Ano Início')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='funcionarios.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_referencia', models.IntegerField()),
                ('ano_referencia', models.IntegerField()),
                ('processada_na_folha', models.BooleanField(default=False)),
                ('credito_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='folha_pagamento.credito')),
            ],
            options={
                'ordering': ['ano_referencia', 'mes_referencia'],
            },
        ),
    ]
