# Generated by Django 5.2.6 on 2026-03-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0005_folhapagamento_total_creditos_manuais_credito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='mes_inicio',
            field=models.IntegerField(default=3, verbose_name='Mês Início (1-12)'),
        ),
        migrations.AlterField(
            model_name='desconto',
            name='mes_inicio',
            field=models.IntegerField(default=3, verbose_name='Mês Início (1-12)'),
        ),
    ]
