# Generated by Django 5.2.6 on 2026-07-12 02:20

import folha_pagamento.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folha_pagamento', '0006_alter_credito_mes_inicio_alter_desconto_mes_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='ano_inicio',
            field=models.IntegerField(default=folha_pagamento.models._ano_atual, verbose_name='Ano Início'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='mes_inicio',
            field=models.IntegerField(default=folha_pagamento.models._mes_atual, verbose_name='Mês Início (1-12)'),
        ),
        migrations.AlterField(
            model_name='desconto',
            name='ano_inicio',
            field=models.IntegerField(default=folha_pagamento.models._ano_atual, verbose_name='Ano Início'),
        ),
        migrations.AlterField(
            model_name='desconto',
            name='mes_inicio',
            field=models.IntegerField(default=folha_pagamento.models._mes_atual, verbose_name='Mês Início (1-12)'),
        ),
    ]
