# Generated by Django 5.2.6 on 2025-09-08 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(max_length=20)),
                ('nome_cliente', models.CharField(max_length=255)),
                ('modelo_veiculo', models.CharField(max_length=100)),
                ('valor_estimado_veiculo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fonte_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte do Cliente')),
                ('quantidade_ligacoes', models.IntegerField(default=0, verbose_name='Quantidade de Ligações')),
                ('data_primeiro_contato', models.DateTimeField(auto_now_add=True)),
                ('data_ultimo_contato', models.DateTimeField(auto_now=True)),
                ('data_proximo_contato', models.DateTimeField()),
                ('tipo_contato', models.CharField(choices=[('Mensagem', 'Mensagem'), ('Audio', 'Áudio'), ('Video', 'Vídeo'), ('Ligacao', 'Ligação'), ('Outro', 'Outro')], max_length=20)),
                ('status_negociacao', models.CharField(choices=[('Novo', 'Novo'), ('Pendente', 'Pendente'), ('Em atendimento', 'Em atendimento'), ('Fechamento', 'Fechamento'), ('Sem resposta', 'Sem resposta'), ('Finalizado', 'Finalizado')], default='Novo', max_length=20)),
                ('proximo_passo', models.CharField(choices=[('Audio', 'Áudio'), ('Mensagem', 'Mensagem'), ('Ligacao', 'Ligação'), ('Video', 'Vídeo'), ('Outro', 'Outro')], max_length=20)),
                ('prioridade', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_interacao', models.DateTimeField(auto_now_add=True)),
                ('motivacao', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-data_interacao'],
            },
        ),
    ]
