# Generated by Django 5.2.6 on 2025-09-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='valor_estimado_veiculo',
            field=models.CharField(max_length=255),
        ),
    ]
