# Generated by Django 5.2.6 on 2025-09-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_valor_estimado_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='prioridade',
            field=models.CharField(choices=[('Frio', 'Frio'), ('Morno', 'Morno'), ('Quente', 'Quente')], default='Morno', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_estimado_veiculo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
