# Generated by Django 5.2.6 on 2025-10-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_alter_cliente_valor_estimado_veiculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_negociacao',
            field=models.CharField(choices=[('Venda', 'Venda'), ('Consignacao', 'Consignação'), ('Outro', 'Outro')], default='Venda', max_length=20, verbose_name='Tipo de Negociação'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='valor_estimado_veiculo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor Estimado do Veículo'),
        ),
    ]
