# Generated by Django 5.2.6 on 2025-10-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_tipo_negociacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ano_veiculo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Ano do Veículo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='marca_veiculo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca do Veículo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='modelo_veiculo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do Veículo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status_negociacao',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Pendente', 'Pendente'), ('Em atendimento', 'Em atendimento'), ('Agendado', 'Agendado'), ('Vendido', 'Vendido'), ('Fechamento', 'Fechamento'), ('Sem resposta', 'Sem resposta'), ('Finalizado', 'Finalizado')], default='Novo', max_length=20),
        ),
    ]
