# Generated by Django 5.2.6 on 2026-05-29 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientes", "0007_cliente_tipo_veiculo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="data_ultimo_andamento",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Último andamento"),
        ),
        migrations.AddField(
            model_name="cliente",
            name="etapa_funil",
            field=models.CharField(
                choices=[
                    ("Recepcao", "Recepção do lead"),
                    ("Qualificacao", "Qualificação"),
                    ("Apresentacao", "Apresentação do veículo"),
                    ("Proposta", "Proposta"),
                    ("Negociacao", "Negociação"),
                    ("Fechamento", "Fechamento"),
                    ("Pos-venda", "Pós-venda"),
                    ("Encerrado", "Encerrado"),
                ],
                default="Recepcao",
                max_length=20,
                verbose_name="Etapa do Funil",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="status_contato",
            field=models.CharField(
                choices=[
                    ("Nao contatado", "Não contatado"),
                    ("Tentativa", "Tentativa de contato"),
                    ("Contato realizado", "Contato realizado"),
                    ("Aguardando retorno", "Aguardando retorno"),
                    ("Sem interesse", "Sem interesse"),
                    ("Fechado com sucesso", "Fechado com sucesso"),
                    ("Perdido", "Perdido"),
                ],
                default="Nao contatado",
                max_length=25,
                verbose_name="Status do Contato",
            ),
        ),
        migrations.CreateModel(
            name="LeadAndamento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "status_contato",
                    models.CharField(
                        choices=[
                            ("Nao contatado", "Não contatado"),
                            ("Tentativa", "Tentativa de contato"),
                            ("Contato realizado", "Contato realizado"),
                            ("Aguardando retorno", "Aguardando retorno"),
                            ("Sem interesse", "Sem interesse"),
                            ("Fechado com sucesso", "Fechado com sucesso"),
                            ("Perdido", "Perdido"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "etapa_funil",
                    models.CharField(
                        choices=[
                            ("Recepcao", "Recepção do lead"),
                            ("Qualificacao", "Qualificação"),
                            ("Apresentacao", "Apresentação do veículo"),
                            ("Proposta", "Proposta"),
                            ("Negociacao", "Negociação"),
                            ("Fechamento", "Fechamento"),
                            ("Pos-venda", "Pós-venda"),
                            ("Encerrado", "Encerrado"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proximo_passo",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Audio", "Áudio"),
                            ("Mensagem", "Mensagem"),
                            ("Ligacao", "Ligação"),
                            ("Video", "Vídeo"),
                            ("Outro", "Outro"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("data_proxima_acao", models.DateTimeField(blank=True, null=True)),
                ("comentario", models.TextField()),
                (
                    "cliente",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="andamentos", to="clientes.cliente"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="andamentos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Andamento do Lead",
                "verbose_name_plural": "Andamentos dos Leads",
                "ordering": ["-criado_em"],
            },
        ),
    ]
