# Generated by Django 5.2.6 on 2026-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacao',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
