# Generated by Django 5.2.6 on 2025-12-21 23:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('cliente_nome', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('tipo_produto', models.CharField(choices=[('GARANTIA', 'Seguro Garantia (Mecânica)'), ('SEGURO', 'Seguro Veículo (Adesão)'), ('TRANSFERENCIA', 'Transferência / Despachante')], max_length=20)),
                ('custo_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo/Base da Loja')),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado do Cliente')),
                ('comissao_vendedor', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('lucro_loja', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Conferência'), ('APROVADO', 'Aprovado pelo Gerente'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10)),
                ('data_venda', models.DateField(default=django.utils.timezone.now)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_produtos', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas_produtos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venda de Produto/Serviço',
                'verbose_name_plural': 'Vendas de Produtos',
                'ordering': ['-data_venda'],
            },
        ),
    ]
