# Generated by Django 5.2.6 on 2025-12-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendaproduto',
            name='tipo_produto',
            field=models.CharField(choices=[('GARANTIA', 'Seguro Garantia (Mecânica)'), ('SEGURO', 'Seguro Veículo (Novo)'), ('TRANSFERENCIA', 'Transferência / Despachante')], max_length=20),
        ),
    ]
