# Generated by Django 5.2.6 on 2025-12-21 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0002_alter_vendaproduto_tipo_produto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendaproduto',
            options={'ordering': ['-data_venda', '-data_criacao'], 'verbose_name': 'Venda de Produto/Serviço', 'verbose_name_plural': 'Vendas de Produtos'},
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='motivo_recusa',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Recusa'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='custo_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Real / Base'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='data_venda',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Venda'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
