# Generated by Django 5.2.6 on 2025-12-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0003_alter_vendaproduto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='banco_financiamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco Financiador'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='comprovante',
            field=models.FileField(blank=True, null=True, upload_to='comprovantes_vendas/', verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix'), ('TRANSFERENCIA', 'Transferência Bancária'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('FINANCIAMENTO', 'Incluso no Financiamento')], default='PIX', max_length=20, verbose_name='Forma de Pagamento'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='numero_proposta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº da Proposta'),
        ),
    ]
