# Generated by Django 5.2.6 on 2025-12-22 00:10

import crmspagi.storage_backends
import vendas_produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0004_vendaproduto_banco_financiamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendaproduto',
            name='comprovante',
            field=models.FileField(blank=True, null=True, storage=crmspagi.storage_backends.PublicMediaStorage(), upload_to=vendas_produtos.models.get_comprovante_upload_path, verbose_name='Comprovante de Pagamento'),
        ),
    ]
