# Generated by Django 5.2.6 on 2025-12-24 13:13

import crmspagi.storage_backends
import django.utils.timezone
import vendas_produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0005_alter_vendaproduto_comprovante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendaproduto',
            options={'ordering': ['-data_venda', '-data_criacao']},
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='arquivo_apolice',
            field=models.FileField(blank=True, null=True, storage=crmspagi.storage_backends.PublicMediaStorage(), upload_to=vendas_produtos.models.get_apolice_upload_path, verbose_name='PDF da Apólice'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='numero_apolice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº da Apólice'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='banco_financiamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='comprovante',
            field=models.FileField(blank=True, null=True, storage=crmspagi.storage_backends.PublicMediaStorage(), upload_to=vendas_produtos.models.get_comprovante_upload_path),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='custo_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='data_venda',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix'), ('TRANSFERENCIA', 'Transferência Bancária'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('FINANCIAMENTO', 'Incluso no Financiamento')], default='PIX', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='motivo_recusa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='numero_proposta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
