# Generated by Django 5.2.6 on 2026-01-10 23:54

import crmspagi.storage_backends
import django.utils.timezone
import vendas_produtos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0006_alter_vendaproduto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendaproduto',
            options={'ordering': ['-data_venda', '-data_criacao'], 'verbose_name': 'Venda de Produto/Serviço', 'verbose_name_plural': 'Vendas de Produtos'},
        ),
        migrations.RemoveField(
            model_name='vendaproduto',
            name='forma_pagamento',
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='com_desconto',
            field=models.BooleanField(default=False, verbose_name='Houve desconto na venda?'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='modelo_veiculo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do Veículo'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='pgto_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor no Crédito'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='pgto_debito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor no Débito'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='pgto_financiamento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Financiado'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='pgto_pix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor em Pix'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='pgto_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor em Transferência'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='banco_financiamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco Financiador'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='comprovante',
            field=models.FileField(blank=True, null=True, storage=crmspagi.storage_backends.PublicMediaStorage(), upload_to=vendas_produtos.models.get_comprovante_upload_path, verbose_name='Comprovante de Pagamento'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='custo_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Real / Base'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='data_venda',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Venda'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='motivo_recusa',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo da Recusa'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='numero_proposta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº da Proposta'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='tipo_produto',
            field=models.CharField(choices=[('VENDA_VEICULO', 'Venda de Veículo'), ('GARANTIA', 'Seguro Garantia (Mecânica)'), ('SEGURO', 'Seguro Veículo (Novo)'), ('TRANSFERENCIA', 'Transferência / Despachante')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Cobrado do Cliente'),
        ),
    ]
