# Generated by Django 5.2.6 on 2026-01-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0007_alter_vendaproduto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='ano',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Ano (Ex: 2023/2024)'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='cor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='modelo_veiculo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
    ]
