# Generated by Django 5.2.6 on 2026-01-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0008_vendaproduto_ano_vendaproduto_cor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='qtd_parcelas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Qtd. Parcelas'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='valor_parcela',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Parcela'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='valor_retorno_operacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retorno da Operação'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='tipo_produto',
            field=models.CharField(choices=[('VENDA_VEICULO', 'Venda de Veículo'), ('GARANTIA', 'Seguro Garantia (Mecânica)'), ('SEGURO', 'Seguro Veículo (Novo)'), ('TRANSFERENCIA', 'Transferência / Despachante'), ('REFINANCIAMENTO', 'Refinanciamento de Veículo')], max_length=20),
        ),
    ]
