# Generated by Django 5.2.6 on 2026-01-28 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0009_vendaproduto_qtd_parcelas_vendaproduto_valor_parcela_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='comissao_ajudante',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='vendedor_ajudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_ajudadas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor Ajudante (Split)'),
        ),
    ]
