# Generated by Django 5.2.6 on 2026-02-02 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0010_vendaproduto_comissao_ajudante_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoMensal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('data_fechamento', models.DateTimeField(auto_now=True, verbose_name='Data do Fechamento')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
            ],
            options={
                'verbose_name': 'Fechamento Mensal',
                'verbose_name_plural': 'Fechamentos Mensais',
                'unique_together': {('mes', 'ano')},
            },
        ),
    ]
