# Generated by Django 5.2.6 on 2026-02-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0011_fechamentomensal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao_carro_padrao', models.DecimalField(decimal_places=2, default=500.0, max_digits=10, verbose_name='Comissão Carro (Padrão)')),
                ('comissao_carro_desconto', models.DecimalField(decimal_places=2, default=200.0, max_digits=10, verbose_name='Comissão Carro (c/ Desconto)')),
                ('comissao_moto', models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Comissão Moto')),
                ('comissao_consignacao', models.DecimalField(decimal_places=2, default=350.0, max_digits=10, verbose_name='Comissão Consignação')),
                ('comissao_compra', models.DecimalField(decimal_places=2, default=350.0, max_digits=10, verbose_name='Comissão Compra/Captura')),
                ('garantia_custo', models.DecimalField(decimal_places=2, default=997.0, max_digits=10, verbose_name='Custo Garantia (Provider)')),
                ('garantia_base', models.DecimalField(decimal_places=2, default=1300.0, max_digits=10, verbose_name='Preço Base Garantia')),
                ('seguro_novo_ref', models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Ref. Comissão Seguro Novo')),
                ('split_transferencia', models.DecimalField(decimal_places=2, default=0.3, max_digits=5, verbose_name='Split Transf. (Vendedor %)')),
                ('split_refin', models.DecimalField(decimal_places=2, default=0.3, max_digits=5, verbose_name='Split Refin. (Vendedor %)')),
                ('split_ajudante', models.DecimalField(decimal_places=2, default=0.5, max_digits=5, verbose_name='Split Ajudante (%)')),
            ],
            options={
                'verbose_name': 'Configuração de Comissões',
                'verbose_name_plural': 'Configuração de Comissões',
            },
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='tipo_produto',
            field=models.CharField(choices=[('VENDA_VEICULO', 'Venda de Veículo'), ('VENDA_MOTO', 'Venda de Moto'), ('CONSIGNACAO', 'Consignação'), ('COMPRA', 'Compra de Veículo'), ('GARANTIA', 'Seguro Garantia (Mecânica)'), ('SEGURO', 'Seguro Veículo (Novo)'), ('TRANSFERENCIA', 'Transferência / Despachante'), ('REFINANCIAMENTO', 'Refinanciamento de Veículo')], max_length=20),
        ),
    ]
