# Generated by Django 5.2.6 on 2026-02-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0012_parametroscomissao_alter_vendaproduto_tipo_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametroscomissao',
            name='comissao_compra',
        ),
        migrations.AlterField(
            model_name='parametroscomissao',
            name='comissao_consignacao',
            field=models.DecimalField(decimal_places=2, default=350.0, max_digits=10, verbose_name='Comissão Consignação/Compra'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Negociado / Cobrado'),
        ),
    ]
