# Generated by Django 5.2.6 on 2026-02-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0013_remove_parametroscomissao_comissao_compra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendaproduto',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Negociado / Cobrado'),
        ),
    ]
