# Generated by Django 5.2.6 on 2026-02-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0014_alter_vendaproduto_valor_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroscomissao',
            name='split_refin',
            field=models.DecimalField(decimal_places=2, default=0.35, max_digits=5, verbose_name='Split Refin. (Vendedor %)'),
        ),
    ]
