# Generated by Django 5.2.6 on 2026-03-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0016_vendaproduto_origem_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendaproduto',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente de Conferencia'), ('APROVADO', 'Aprovado pelo Gerente'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=10),
        ),
    ]
