# Generated by Django 5.2.6 on 2026-07-03 20:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0018_vendaproduto_campos_minuta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametroscomissao',
            name='split_refin',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.35'), max_digits=5, verbose_name='Split Refin. (Vendedor %)'),
        ),
        migrations.AlterField(
            model_name='parametroscomissao',
            name='split_transferencia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.30'), max_digits=5, verbose_name='Split Transf. (Vendedor %)'),
        ),
    ]
