# Generated by Django 5.2.6 on 2026-07-06 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0020_alter_vendaproduto_vendedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='comprovante_ia_observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação da IA'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='comprovante_status_ia',
            field=models.CharField(choices=[('NAO_VERIFICADO', 'Não verificado'), ('VALIDO', 'Válido (IA)'), ('INVALIDO', 'Inválido (IA)'), ('MANUAL', 'Validado Manualmente')], default='NAO_VERIFICADO', max_length=20, verbose_name='Status da Validação (IA)'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='comprovante_validado_manual_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Validado manualmente em'),
        ),
        migrations.AddField(
            model_name='vendaproduto',
            name='comprovante_validado_manual_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprovantes_validados_manualmente', to=settings.AUTH_USER_MODEL, verbose_name='Validado manualmente por'),
        ),
    ]
