# Generated by Django 5.2.6 on 2026-07-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas_produtos', '0021_vendaproduto_comprovante_ia_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaproduto',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
